
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import { Providers } from './provider'
import { redirect } from 'next/navigation'
import LoadingStatus from '@/components/LoadingStatus'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <LoadingStatus/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
