
import SideBar from '@/components/SideBar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getUsers } from '../action/getUsers'
import { UserList } from './components/UserList'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const users = await getUsers()

  return (
    //@ts-expect-error Server Component
    <SideBar>
      <div className='h-full'>
        <UserList items={users} />
        {children}
      </div>
    </SideBar>
  )
}
